### ISSUE TITLE
Developer ID not trusted by Gatekeeper

### ISSUE THREAD

**Issue by fumoboy007** [hbwhite/Clutch#2]
Downloading the pre-built app from the [Transmission forum post](https://forum.transmissionbt.com/viewtopic.php?t=18944#p76089) and trying to open it presents a warning dialog saying `“Clutch” can’t be opened because it is from an unidentified developer.` Tested on macOS 10.14 Beta 7.

**Comment by hbwhite** [comment]
You can open the app by right-clicking it and selecting “Open” from the menu, then confirming that you want to open it.

I’ll consider signing a future version of the app to prevent this, if it becomes an issue for more people. Thanks!
