### ISSUE TITLE
How do I identify the interface for the VPN?

### ISSUE THREAD

**Issue by m3stu** [hbwhite/Clutch#4]
Hi,

Not an issue, as such, but I have 4 utun interfaces available in the drop down list and an ipsec0 interface which shows the IP address that I can see assigned by the VPN provider.

How do I know which interface to choose?

Sorry if this is a silly question!

**Comment by hbwhite** [comment]
It should be the ipsec0 interface if that’s the one with the IP from the VPN provider. (Are you using L2TP?) An easy way to check is to look at the list before you connect to the VPN and see what new interfaces appear after you connect.
