### ISSUE TITLE
Feature request: wildcard interface

### ISSUE THREAD

**Issue by khad** [hbwhite/Clutch#6]
My VPN uses a different interface from time to time. Not sure the logic behind it. But the upshot is that iI regularly have to go into Clutch and unbind from the previous interface, then bind to the current interface. I have a list of `utun0`, `utun1`, `utun2`, and so on.

Would it possible to just bind to `utun*`, so I don't have to keep going in to change it?

**Comment by hbwhite** [comment]
Added regex support in v1.4.
Be sure to use real regex and not shell glob. In your case, enter utun.* instead of utun*

You can update to v1.4 via Clutch > Check for Updates, or you can download the app from the "Releases" page on GitHub.

**Comment by khad** [comment]
Thanks for adding regex support! So far so good.
