### ISSUE TITLE
Hide dock icon

### ISSUE THREAD

**Issue by Jottle** [hbwhite/Clutch#8]
Love this app. Thanks for making it free. I try to limit the number of apps appearing in my dock. In the next revision, if possible, would you be able to add an option in the clutch preferences to make it not add a visible clutch icon to the dock when clutch is open and running? Given that there's the clutch menubar icon always present when the agent is up, it would be nice to not also have the app icon appear in the dock. 

Thanks

**Comment by hbwhite** [comment]
Hi, there shouldn’t be an icon in the dock unless the Clutch setup app is running. There are 2 parts, the Clutch setup app and Clutch Agent. Clutch Agent runs in the background and has the icon in the top bar. If you click the icon in the bottom dock, the Clutch setup app should appear. You can then quit the Clutch setup app (press Command-Q) and Clutch Agent will continue to run in the background.

If you already know this and the icon is appearing in the dock anyway: (1) what version of Mac OS are you running? (2) does this still happen if you restart? (3) what is the output when you run this command in Terminal: “ps aux | grep Clutch”?

Glad you like the app! I made it for myself but I see many people are using it now.

**Comment by Jottle** [comment]
Ah. Thanks for clarifying. I had the setup window open as you mentioned. No issue! Please delete this comment.

**Comment by hbwhite** [comment]
Ah okay; glad it's working properly. I'll leave it up in case anyone else has this question.
